#!/usr/bin/env python
import sys

from pymongo import Connection

from util import edist

points = [[44, 95], [26, 91], [22, 90], [21, 90],
        [19, 89], [17, 89], [15, 87], [15, 86], [16, 85],
        [20, 83], [26, 81], [28, 80], [30, 79], [32, 74],
        [32, 72], [33, 71], [34, 70], [38, 68], [43, 66],
        [49, 64], [52, 63], [52, 62], [53, 59], [54, 57],
        [56, 56], [57, 56], [58, 56], [59, 56], [60, 56],
        [61, 55], [61, 55], [63, 55], [64, 55], [65, 54],
        [67, 54], [68, 54], [76, 53], [82, 52], [84, 52],
        [87, 51], [91, 51], [93, 51], [95, 51], [98, 50],
        [105, 50], [113, 49], [120, 48], [127, 48], [131, 47],
        [134, 47], [137, 47], [139, 47], [140, 47], [142, 47],
        [145, 46], [148, 46], [152, 46], [154, 46], [155, 46],
        [159, 46], [160, 46], [165, 46], [168, 46], [169, 45],
        [171, 45], [173, 45], [176, 45], [182, 45], [190, 44],
        [204, 43], [204, 43], [207, 43], [215, 40], [215, 38],
        [215, 37], [200, 37], [195, 41]]


if __name__ == "__main__":
    for i, point in enumerate(points):
        if len(sys.argv) > 1:
            collection = sys.argv[1]
        else:
            collection = "test_graph"

        db = Connection("127.0.0.1", 27017)["osm-data"][collection]
        db.drop()

        successors = []
        if i > 0:
            successors.append({"id": i - 1, "distance": edist(point, points[i - 1])})
        if i < len(points) - 1:
            successors.append({"id": i + 1, "distance": edist(point, points[i + 1])})

        db.insert({
            "_id": i,
            "loc": point,
            "successors": successors,
        })
