#!/usr/bin/env python

from pymongo import Connection


class Database(object):
    def __init__(self, db="osm-data", host="localhost", port=27017):
        self.connection = Connection(host, port)
        self.db = self.connection[db]


class Collection(Database):
    def __init__(self, collection, *args, **kwargs):
        super(Collection, self).__init__(*args, **kwargs)
        self.col = self.db[collection]


class RailwayGraph(Collection):
    def __init__(self, *args, **kwargs):
        super(RailwayGraph, self).__init__("railway_graph", *args, **kwargs)


if __name__ == "__main__":
    rg = RailwayGraph()

    # doubly linked-list?
    print rg.col.find()[0]
