#!/usr/bin/env python
import sys

from pymongo import Connection

from util import edist, create_rg
from data import points

if __name__ == "__main__":
    cname = sys.argv[1] if len(sys.argv) > 1 else "test_graph"
    col = Connection("127.0.0.1", 27017)["osm-data"][cname]

    create_rg(points, col)
