#!/usr/bin/env python

import sys
from pymongo import Connection

from rdp import rdp, epsilon_linear
from segment import segment
from anglered import anglereduce_col

if __name__ == "__main__":
    db = Connection("127.0.0.1", 27017)["osm-data"]["shortest_routes_zoom_level_16"]
    db2 = Connection("127.0.0.1", 27017)["osm-data"]["shortest_routes_zoom_level_9"]
    for n in db.find():
        db2.insert(n)

    sys.exit(0)



    db = Connection("127.0.0.1", 27017)["osm-data"]["railway_graph"]
    db2 = Connection("127.0.0.1", 27017)["osm-data"]["railway_graph2"]
    db2.drop()

    segs = segment(db)
    for seg in segs:
        anglereduce_col(seg, 179.5, db, db2)

    print len(list(db.find()))
    print len(list(db2.find()))
